add algorithm
kirillkuks/SegmentsVisibility pull request #16
Opened 2022-11-27 13:19 UTC by BoIlAl

2022-11-27 13:39 UTC, kirillkuks requested changes

2022-11-27 13:39 UTC, kirillkuks commented on .gitignore
> +n4_algorithm/n4_alg.aux
Лучше заменить на *.aux. Аналогично для других

2022-11-27 13:39 UTC, kirillkuks commented on n4_algorithm/n4_alg.tex
> +      \item $P$ - множесто ограничивающих точек отрезков из $S$.
Может множество концов отрезков

2022-11-27 13:39 UTC, kirillkuks commented on n4_algorithm/n4_alg.tex
> +            Для дальнейшей обработки множество точек $P$ сохраняется в контейнере.
Сохраняется в контейнере можно убрать и оставить просто - сохраняется

2022-11-27 13:39 UTC, kirillkuks commented on n4_algorithm/n4_alg.tex
> +      \item Строится arrangement of lines $A(L)$ с помощью
Может просто упорядочение прямых, раз у нас всё на русском

2022-11-27 13:39 UTC, kirillkuks commented on n4_algorithm/n4_alg.tex
> +            Строится множество $L$, прямых, определяющихся любой парой $p_i, p_j$ из $P$.
Вместо из можно \in

2022-11-27 13:39 UTC, kirillkuks commented on n4_algorithm/n4_alg.tex
> +            по возрастанию полярного угла относительно любой вершины $q$ данной грани.
Вроде вершины не подходят, нужна точка из внутренности грани

2022-11-27 13:39 UTC, kirillkuks commented on n4_algorithm/n4_alg.tex
> +            После сортировки все отрезки проверяются на <<правильность>>
может правильность заменить на видимость

2022-11-27 13:39 UTC, kirillkuks commented on n4_algorithm/n4_alg.tex
> +            Результаты сравниваются и, если они не равны, точки отрезков,
Как-то сложно понять, о чём идет речь. Так как вроде результат прошлого пункта количество видимых отрезков

2022-11-27 15:19 UTC, BoIlAl commented on n4_algorithm/n4_alg.tex
> +            по возрастанию полярного угла относительно любой вершины $q$ данной грани.
А можешь описать, почему они не подходят?

Всегда можно найти рациональную точку внутри непустой грани и считать относительно нее.
Это также уберет следующий абзац текста. 
_Но_. Это упорядочивание далее применяется при проверке на правильность, а там грани могут быть пустыми.

2022-11-27 15:20 UTC, BoIlAl commented on n4_algorithm/n4_alg.tex
> +            После сортировки все отрезки проверяются на <<правильность>>
Мне кажется, стоит дать определение видимости в постановке (так как скорее всего данный термин будет фигурировать много где). Более того, если это определение дать, станет понятно, что оно не согласуется с понятием "правильность" алгоритма.

2022-11-27 15:30 UTC, kirillkuks requested changes

2022-11-27 15:30 UTC, kirillkuks commented on n4_algorithm/n4_alg.tex
> +            После сортировки все отрезки проверяются на <<правильность>>
Определенно стоит дать формальное определение и доказать (или сказать, что очевидно), что отрезок виден тогда и только тогда, когда в его концы соседи в отсортированном массиве

2022-11-27 15:30 UTC, kirillkuks commented on n4_algorithm/n4_alg.tex
> +            После сортировки все отрезки проверяются на <<правильность>>
Но слово правильность точно надо заменить на видимость

2022-11-27 15:30 UTC, kirillkuks commented on n4_algorithm/n4_alg.tex
> +            по возрастанию полярного угла относительно любой вершины $q$ данной грани.
Например если прямая порождается одним отрезком, то с любой точки на ней (вне самого отрезка) видна будет только одна точка этого отрезка - один из его концов

2022-11-27 15:44 UTC, BoIlAl commented on n4_algorithm/n4_alg.tex
> +            по возрастанию полярного угла относительно любой вершины $q$ данной грани.
Если вершина лежит на прямой, которая порождается точками _p_ и _q_, то полярные углы _p_ и _q_ относительно данной вершины равны. Про такие ситуации следующие 4 строчки алгоритма.
Опять же внутренности у грани может просто не быть.

2022-11-28 19:14 UTC, StanislavVolodarskiy commented on n4_algorithm/n4_alg.tex
> +            Точки меняются местами в контейнере, если:
Точки меняют порядок в контейнере в любом случае.

2022-11-28 19:21 UTC, StanislavVolodarskiy commented on n4_algorithm/n4_alg.tex
> +            выбрать точку на грани:
Это всё не нужно. При заметании вся плоскость поделена на сектора. Когда две точки меняются местами, меняется статус только в одном секторе. Точнее один сектор исчезает, на его месте возникает новый сектор с почти таким же статусом. "Почти таким же" - напомните мне нарисовать все случаи. Так или иначе, я берусь обновить статус за константу.

2022-11-28 19:22 UTC, StanislavVolodarskiy commented on n4_algorithm/n4_alg.tex
> +                  \item Если грань непустая выбирается любая внутренняя точка.
Не нужно выбирать точку.

2022-11-28 19:23 UTC, StanislavVolodarskiy commented on n4_algorithm/n4_alg.tex
> +                        %Не может же получиться граней вырожденных в точку?
Двайте заведём МТОП - никакие три точки не лежат на одной прямой и забудем про пустые грани. Они не интересны.

2023-04-01 15:10 UTC, StanislavVolodarskiy approved these changes

2023-04-01 15:10 UTC, StanislavVolodarskiy commented on n4_algorithm/n4_alg.tex
> +            $O(n^4)$.
Ссылку какую-нибудь на работу с алгоритмом построения упорядочения.

2023-04-04 11:58 UTC, kirillkuks approved these changes

2023-04-04 11:58 UTC, merged