Set task
kirillkuks/SegmentsVisibility pull request #7
Opened 2022-11-21 21:44 UTC by kirillkuks

2022-11-27 16:35 UTC, BoIlAl requested changes

2022-11-27 16:35 UTC, BoIlAl commented on README.md
> +S - множество из n непересекающихся отрезков. Определить, существует ли точка p такая, что из неё были бы видны все отрезки из S полностью.
Кажется для дальнейших доказательств необходимо дать определение понятию "видимость"

2022-11-28 19:11 UTC, StanislavVolodarskiy commented on README.md
> +S - множество из n непересекающихся отрезков. Определить, существует ли точка p такая, что из неё были бы видны все отрезки из S полностью.
При круговом заметании в статусе не более одного отрезка. Годится?
Треугольник из точки и отрезка не пересекается с другими отрезками. Годится?
Они эквивалентны.

2023-03-01 15:01 UTC, StanislavVolodarskiy reviewed
It's OK.

2023-03-01 15:02 UTC, BoIlAl approved these changes

2023-03-01 15:03 UTC, StanislavVolodarskiy approved these changes

2023-03-01 15:03 UTC, merged